backend:
  image:
    repository: docker.io/mingpham/yas-sampledata
    tag: d11f41e
  replicaCount: 0
  service:
    type: ClusterIP
  serviceMonitor:
    enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 384Mi
    limits:
      cpu: 700m
      memory: 768Mi
