backend:
  image:
    repository: docker.io/mingpham/yas-tax
    tag: main

  service:
    type: ClusterIP

  serviceMonitor:
    enabled: true

  resources:
    requests:
      cpu: 110m
      memory: 384Mi
    limits:
      cpu: 700m
      memory: 768Mi
