apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-staging-backoffice-ui
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ming1309/yas.git
    targetRevision: gitops-staging
    path: k8s/charts/backoffice-ui
    helm:
      valueFiles:
        - ../../environments/staging/backoffice-ui.values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: yas-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
