apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-staging-customer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ming1309/yas.git
    targetRevision: main
    path: k8s/charts/customer
    helm:
      valueFiles:
        - ../../environments/staging/customer.values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: yas-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
