apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-developer-sampledata
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Ming1309/yas.git
    targetRevision: gitops-developer
    path: k8s/charts/sampledata
    helm:
      valueFiles:
        - ../../environments/developer/sampledata.values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: yas-developer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
