apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-developer-storefront-ui
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ming1309/yas.git
    targetRevision: main
    path: k8s/charts/storefront-ui
    helm:
      valueFiles:
        - ../../environments/developer/storefront-ui.values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: yas-developer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
