ui:
  image:
    repository: docker.io/mingpham/yas-backoffice
    tag: main

  service:
    type: NodePort
    nodePort: 30090

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
