backend:
  image:
    repository: docker.io/mingpham/yas-product
    tag: v1.0.0
  service:
    type: ClusterIP
  serviceMonitor:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 384Mi
    limits:
      cpu: 700m
      memory: 768Mi
