kafka:
  replicas: 1
  version: 3.9.1
  metadataVersion: 3.9-IV0
  storeSize: 10Gi
postgresql:
  username: yasadminuser
  password: admin
debeziumConnect:
  image: docker.io/mingpham/debezium-connect-postgresql:0.47.0
  buildImage: false #Enabled when build debezium-connect-postgresql image
